# Generated by Django 4.2.1 on 2023-06-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gmap_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
