# Generated by Django 4.2.1 on 2023-06-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_place_gmap_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gmap_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
