# Generated by Django 4.2.1 on 2023-06-01 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RangingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('business_id', models.IntegerField()),
                ('api_key', models.CharField(max_length=32, unique=True)),
                ('key_words', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_data', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_datetime', models.TimeField()),
                ('end_datetime', models.TimeField()),
                ('status', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ranking_condition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_shop.rangingcondition')),
            ],
        ),
        migrations.CreateModel(
            name='RankingPalace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ranking_search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_shop.rankingsearch')),
            ],
        ),
    ]
