# Generated by Django 4.2.1 on 2023-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingpalace',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='cid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='price_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingpalace',
            name='rating_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingsearch',
            name='key_words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rankingpalace',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
