# Generated by Django 4.2.1 on 2023-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_shop', '0003_alter_rankingsearch_search_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingsearch',
            old_name='search_data',
            new_name='search_date',
        ),
        migrations.AlterField(
            model_name='rankingsearch',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rankingsearch',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
